### PR TITLE
Add support for `ember-cli-babel` v8

### LINKED ISSUE #1211: Support `ember-cli-babel` v8
Seeing this warning at the moment:

```
WARNING: ember-test-selectors: You are using an unsupported ember-cli-babel version. data-test properties are not automatically stripped from your JS code.
```

Though, it seems stripping `data-test` selectors does still work.

EDIT: We don't use `data-test` selectors in JS land, so that's why the results I'm seeing are still the same.

### PR DESCRIPTION
**Pull request by bertdeblock**
Builds on #1212.

Closes #1211.

### CODE REVIEW

**Comment by jrjohnson** [comment]
@marcoow or @Turbo87 (the last two non renovate commiters here). Can someone take a look at this? With `ember-cli-babel` v8 in the default blueprint this change is very much needed.

**Comment by marcoow** [comment]
@bertdeblock can you rebase on #1212?

**Comment by bertdeblock** [comment]
@marcoow Rebased.

**Review by marcoow — APPROVED** [review]

**Comment by marcoow** [comment]
@bertdeblock tests fail with latest Ember versions…

**Comment by bertdeblock** [comment]
That's already the case on `master`, so unrelated to this PR AFAICT.
Seems like the dummy app needs a bit of maintenance.

**Comment by marcoow** [comment]
ah I see

**Comment by Windvis** [comment]
@marcoow Is there any chance we can get a new release that includes this change? 🙏

**Comment by bertdeblock** [comment]
https://github.com/mainmatter/ember-test-selectors/pull/1216 fixes CI, can someone cut a release?

**Comment by gorner** [comment]
@bertdeblock @marcoow any updates on a new release? I see #1216 was closed without merging but I'm not sure why.

**Pull request merged**
